### ISSUE TITLE
Chrome KeePass: " Something went wrong"

### ISSUE THREAD

**Issue by aaronmue** [RoelVB/ChromeKeePass#105] opened 2024-04-30 09:40 UTC
![image](https://github.com/RoelVB/ChromeKeePass/assets/168534942/7c4b699f-6824-4290-b80b-0b26d137b21d)

KeePass was not working anymore tried to reinstall it but there is no possibility to reconnect to KeePass

**Comment by RoelVB** [comment] 2024-04-30 17:46
I assume you've checked if KeePassHttp is installed and you're connecting to the correct port?

You could you try this:
- Put your browser into developer mode (chrome://extensions -> "developermode" toggle at the top)
- Open the "backgroundpage" for ChromeKeePass
- Try to connect CKP again
- Check the "Network" tab of the backgroundpage
- The request to http://localhost:19455/ could shows some additional information
- If you want you could "Export to HAR" (last icon below the tabbar) and share it here

**Comment by SAMUD** [comment] 2024-05-03 06:18
I am having the same message in Edge. However in Chrome the addon is connecting just fine.
What du you mean by "backgroundpage"? If I open the DevTools for the Plugin under Network it shows me this:
![image](https://github.com/RoelVB/ChromeKeePass/assets/10502656/21496bdf-27b9-4245-a176-61ef3fe24d40)

Also I am not sure what you mean with "export to HAR". Where do I find this?

**Comment by RoelVB** [comment] 2024-05-04 14:55
@SAMUD 
That's the correct DevTools. This is the export icon:
<img width="660" alt="image" src="https://github.com/RoelVB/ChromeKeePass/assets/10999128/0d73a21a-9835-44e5-ba83-e3556a609474">

What version of Edge are you on? I don't have any issue on version 124.0.2478.80.

**Comment by SAMUD** [comment] 2024-05-10 12:38
I'm on 124.0.2478.80 too....

Here is the HAR:

[jnhjknbfnclancjpknceboifoegiompf.zip](https://github.com/RoelVB/ChromeKeePass/files/15275094/jnhjknbfnclancjpknceboifoegiompf.zip)

**Comment by RoelVB** [comment] 2024-05-10 12:46
@SAMUD 
Thanks you for the file.

It seems that something or some setting forces ChromeKeePass to use HTTPS. KeePassHttp doesn't support HTTPS, it sends encrypted data over HTTP.
Do you maybe have another extension installed that forces websites to use HTTPS?

**Comment by RoelVB** [comment] 2024-05-10 12:50
@SAMUD 
Can you check open this page in Edge `edge://net-internals/#hsts` and see if `localhost` is listed there? That could cause the issue.

**Comment by gschizas** [comment] 2024-05-14 19:01
I have the same problem, and I just did low level troubleshooting with WireShark, and it was indeed trying to do a TLSv1 handshake before. And this only worked on ONE profile (my other profile was fine).

localhost was indeed found in the hsts/pkp domains, and after deleting it (I didn't think to record the result of the query though), it started working again!

I believe this all was a result of Visual Studio running a site on https://localhost/

**Comment by RoelVB** [comment] 2024-05-15 16:14
@gschizas Thank you for letting us know.
I'm going to assume it's the same for the others here and close this issue.

**Closed as completed by RoelVB** 2024-05-15 16:14 UTC

**Comment by RoelVB** [comment] 2024-05-16 07:22
I was just thinking. Changing the "Hostname / IP address" in the ChomeKeePass settings to `127.0.0.1` will probably also resolve this issue.

**Comment by SAMUD** [comment] 2024-05-17 08:22
@RoelVB there is nothing listed in `edge://net-internals/#hsts`

I have multiple softwares installed which runs websites on localhost (thanks Siemens...) and uses https.

I fixed it by switching to `127.0.0.1`...

Thanks for your help!

**Comment by gschizas** [comment] 2024-05-17 08:24
@SAMUD, you need to go to the "Query HSTS/PKP domain" section, type "localhost" and press "Query"

**Comment by SAMUD** [comment] 2024-05-17 08:27
@gschizas i dont want to delete the entry. Siemens stuff is sometimes very picky... And I don't want to break it. So changing to 127... ist the easier method :)

**Comment by gschizas** [comment] 2024-05-17 08:30
@SAMUD you don't need to delete the entry, I just said to press "query", to provide info for this bug.

In any case, this won't stop any program from running on localhost. This setting is that Edge (specifically) auto redirects http://localhost to https://localhost. Your Siemens stuff will probably be fine.

**Comment by SAMUD** [comment] 2024-05-17 08:41
![image](https://github.com/RoelVB/ChromeKeePass/assets/10502656/a1047b94-7fe7-499c-bc95-d28270ac6bfe)

@gschizas

**Comment by gschizas** [comment] 2024-05-17 09:55
Yeap, this looks like what I saw. I think you'll be ok to delete this; this is not only Edge specific, it's specific to the profile of Edge you're using. But if you got a different workaround, that's ok too. The point is that we found the cause of the error, and it was the same, and it was correctly closed.
